"""client_id truely

Revision ID: 33833e1d4e9c
Revises: 4f2e278c5df3
Create Date: 2023-02-25 13:40:18.717236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33833e1d4e9c'
down_revision = '4f2e278c5df3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reg', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('reg', schema=None) as batch_op:
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
