"""empty message

Revision ID: 804db3b6b8a9
Revises: 
Create Date: 2023-01-29 01:13:48.061674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804db3b6b8a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data', sa.VARCHAR(length=10000), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=250), nullable=True),
    sa.Column('password', sa.VARCHAR(length=150), nullable=True),
    sa.Column('fullname', sa.VARCHAR(length=250), nullable=True),
    sa.Column('comment', sa.VARCHAR(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
