"""first try

Revision ID: 823dd71ea3fc
Revises: 804db3b6b8a9
Create Date: 2023-02-20 16:44:34.664970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823dd71ea3fc'
down_revision = '804db3b6b8a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reg', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_fullname', sa.String(), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'user', ['user_fullname'], ['fullname'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reg', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('date',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.drop_column('user_fullname')

    # ### end Alembic commands ###
